### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined(anonymous function) 

### ISSUE THREAD

**Issue by CBke** [agershun/alasql#531] opened 2016-01-14 16:33 UTC
I got the error:

Uncaught TypeError: Cannot read property '0' of undefined
[issue.txt](https://github.com/agershun/alasql/files/90666/issue.txt)

Could reproduce it in http://alasql.org/console/

CBke

**Comment by agershun** [comment] 2016-01-14 16:35
```sql
create table data( id INTEGER PRIMARY KEY);
insert into data values (1);
insert into data values (2);

select a.id , ifNULL((select MIN(b.id) from data as b where a.id < b.id), 0) b_id from data as a;

create view view1 as select a.id , ifNULL((select MIN(b.id) from data as b where a.id < b.id), 0) b_id from data as a;

select * from view1;
```

**Comment by agershun** [comment] 2016-01-14 22:34
I discovered this issue. The problem is that AlaSQL can not run ```SELECT``` subqueries from ```VIEW``` query. Probably we can not solve it in short-term. Sorry,

**Comment by mathiasrw** [comment] 2016-03-19 12:12
Closed as its put on The Long List - only to be reopend when its time has come.

**Closed by mathiasrw** 2016-03-19 12:12 UTC
Labels: ! Bug, Bug: Code provided to reproduced
