### ISSUE TITLE
Error: TypeError: Unable to get property 'sourcefilename' of undefined or null reference

### ISSUE THREAD

**Issue by schinta2** [agershun/alasql#919] opened 2017-07-26 18:37 UTC
Are any of the options needed while creating a new excel sheet using 'select * into XLS'?

The below code is failing with a valid JSON object(data)
alasql.promise('SELECT * INTO XLSX("test.xlsx") FROM ?', [data])
.then( function(data) {console.log('exported')})
.catch( function(err) {console.log('Error:', err)});

couldn't find documentation related to the error code in the subject. Any help is truly appreciated

Finding this issue on IE 11

**Comment by mathiasrw** [comment] 2017-07-28 10:20
Hmm. Cant replicate. 

what is in the `data` var?

**Comment by mathiasrw** [comment] 2017-08-16 10:31
Closing. Please reopen if you have more information.

**Comment by sebastianhakansson** [comment] 2018-05-03 13:15
This error disappears if you provide options for the XLSX function, e.g:

`var alasql = require('alasql');
var data = [{a:1,b:1,c:1},{a:1,b:2,c:1},{a:1,b:3,c:1}, {a:2,b:1,c:1}];

alasql.promise('SELECT * INTO XLSX("demo.xlsx", {headers:true}) FROM ?', [data])
            .then(function(data){
                 console.log(data);
            }).catch(function(err){
                 console.log('Error:', err);
            });`

**Comment by sebastianhakansson** [comment] 2018-05-03 13:16
This error disappears if you provide options for the XLSX function, e.g:

```
var alasql = require('alasql');
var data = [{a:1,b:1,c:1},{a:1,b:2,c:1},{a:1,b:3,c:1}, {a:2,b:1,c:1}];

alasql.promise('SELECT * INTO XLSX("demo.xlsx", {headers:true}) FROM ?', [data])
.then(function(data){
console.log(data);
}).catch(function(err){
console.log('Error:', err);
});
```

**Comment by mnmallea** [comment] 2020-08-19 04:54
I have the same error and it solves when passing an object to the options params (also works with an empty object).
I think the problem is in this line https://github.com/agershun/alasql/blob/10231230456dba00f3e263f6752ab5b6ed16c389/dist/alasql.js#L17046
And opts object probably should have a default to `{}`

**Closed** 2020-08-21 02:27 UTC
Labels: ! Bug, Bug: Code provided to reproduced, Good first issue, Help wanted
