### ISSUE TITLE
primary key index left behind after all data from table was deleted

### ISSUE THREAD

**Issue by dmvianna** [agershun/alasql#427] opened 2015-09-25 03:24 UTC
This is puzzling. This synchronous code tells me the table is empty, but then I cannot add data because the primary keys are still lying around.

Example, live in [Codepen](http://codepen.io/dmvianna/pen/meroeM) (open console and refresh to see all the action):

```javascript
    <script src="https://cdn.jsdelivr.net/alasql/0.2.0/alasql.min.js"></script>
    <script>
      function range(i){return i?range(i-1).concat({'id': i}):[]}
      data = range(100);
      db = new alasql.Database('db');
      db.exec("CREATE TABLE test (id INT NOT NULL PRIMARY KEY)");
      db.exec("INSERT INTO test SELECT * FROM ?", [data]);
      console.table(db.exec("SELECT * FROM test"));
      db.exec("DELETE FROM test");
      db.exec("INSERT INTO test SELECT * FROM ?", [data]);
      console.table(db.exec("select * from test"))
    </script>
```
If you open your browser's console, you'll see that `.deleteAll()` hasn't finished by the time we start adding the rows again. Instead, we get

`Uncaught Error: Cannot insert record, because it already exists in primary key index`

**Comment by mathiasrw** [comment] 2015-09-25 07:26
Ohh, nice catch. Thanks for letting us know...

I dont have time to look at it before the weekend.

If you find out anything else let me know...

**Comment by kakarias** [comment] 2015-12-10 19:31
I have similar problem. I have created TABLE wih primary key. Then i tried to Truncate it with using 'DELETE FROM dummyTable' and then i tried to insert new row with used key before and it throw me this error 'Cannot insert record, because it already exists in primary key index'. I'll try drop the table and ill see if its works. I'll let you know.

**Comment by kakarias** [comment] 2015-12-10 21:59
I had to drop table and create again and then it starts work.

**Comment by agershun** [comment] 2015-12-11 06:27
I understand where is the problem. DeleteAll proWe will fix it.

We need to add this line:
```js
		db.dbversion++;
```
after the line 106 of 72delete.js:
```js
			db.tables[tableid].data.length = 0;
```
This will reset all keys in the table.

**Comment by agershun** [comment] 2015-12-11 06:41
Fixed. Please see [text378](https://github.com/agershun/alasql/blob/develop/test/test378.js). Thank you for the bug!

**Comment by mathiasrw** [comment] 2015-12-11 12:33
I can confirm that running the original script gave error and changing the library to https://cdn.rawgit.com/agershun/alasql/f518d6dcc59c864763a0ae4be39ae7ffde23d227/dist/alasql.min.js gave correct result. 

The test378 looks good with the asserts and I can see it has passed when comitted: https://travis-ci.org/agershun/alasql/builds/96211128

so all god - im closing this issue...

**Closed by mathiasrw** 2015-12-11 12:33 UTC
Labels: Bug, solved please test

**Comment by kakarias** [comment] 2015-12-11 15:08
Great job guys
